# Generated by Django 3.1.3 on 2020-11-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_num', models.CharField(max_length=50)),
                ('incident_type', models.CharField(max_length=50)),
                ('occured_date_time', models.DateField()),
                ('precinct', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('beat', models.CharField(max_length=50)),
                ('officer_id', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('subject_race', models.CharField(max_length=50)),
                ('subject_gender', models.CharField(max_length=50)),
            ],
        ),
    ]
