# Generated by Django 3.1.3 on 2020-11-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='occured_date_time',
            field=models.DateTimeField(),
        ),
    ]
